name: build docker image

on: push
jobs:
    push_to_registry:
        name: Checkout code
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: login to docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: build image
          uses: docker/build-push-action@v2
          with:
            context: DockerFileFolder/
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/dockergithub

            